# Generated by Django 5.1.1 on 2025-01-30 14:16

import core.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recursos_rename_instagran_funcionario_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modificados', models.DateTimeField(auto_created=True, verbose_name='Atualizacao')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('profissao', models.CharField(max_length=50, verbose_name='Cargo')),
                ('descricao', models.TextField(max_length=400, verbose_name='Relato')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem')),
                ('icone', models.CharField(choices=[('lni-star-filled', 'EstrelaCheia'), ('lni-star-half', 'EstrelaVazia')], max_length=15, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
