# Generated by Django 5.1.1 on 2025-01-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='estrelas',
            field=models.IntegerField(default=3, verbose_name='Estrelas'),
        ),
    ]
