# Generated by Django 5.1.1 on 2025-01-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clientes_estrelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='estrelas',
            field=models.IntegerField(default=3, verbose_name='Quantidade de Estrelas'),
        ),
    ]
