# Generated by Django 5.1.1 on 2025-02-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_clientes_estrelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='icone',
            field=models.CharField(choices=[("'lni-star-filled','lni-star-half','lni-star-half','lni-star-half','lni-star-half', ", 'UmaEstrelaCheia'), (" 'lni-star-filled','lni-star-filled','lni-star-half','lni-star-half','lni-star-half' ", 'DuasEstrelaCheias')], max_length=100, verbose_name='Icone'),
        ),
    ]
