# Generated by Django 5.1.1 on 2025-02-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_clientes_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='estrelas',
            field=models.IntegerField(verbose_name='Quantidade de Estrelas'),
        ),
    ]
