# Generated by Django 5.1.1 on 2025-02-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_clientes_estrelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='icone',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='estrelas',
            field=models.IntegerField(help_text='Escolha de 1 a 5', max_length=5, verbose_name='Quantidade de Estrelas'),
        ),
    ]
