# Generated by Django 5.1.1 on 2025-02-03 12:01

import core.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_clientes_icone_alter_clientes_estrelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='estrelas',
            field=models.IntegerField(help_text='Escolha de 1 à 5', max_length=5, verbose_name='Quantidade de Estrelas'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 75, 'width': 75}}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-laptop-phone', 'Not-celular'), ('lni-cog', 'Engrenagem'), ('lni-leaf', 'Folha'), ('lni-layers', 'Camadas'), ('lni-leaf', 'Folha')], max_length=17, verbose_name='Icone'),
        ),
    ]
